# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-08-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_auto_20260814_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
