# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-08-18 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
