# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-08-18 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_mascota_imagen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mascota',
            table='files',
        ),
    ]
