# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-08-18 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0007_auto_20260818_1554'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mascota',
            table=None,
        ),
    ]
